# Generated by Django 2.2 on 2019-11-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=200)),
                ('expected_time', models.CharField(blank=True, max_length=200)),
                ('candidate_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('roll_number', models.CharField(max_length=50)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_interview', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('cpoc', models.CharField(max_length=200)),
                ('cpoc_contact', models.CharField(max_length=200)),
                ('all_candidate', models.ManyToManyField(blank=True, related_name='all_person', to='dday_portal.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='eligible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi', models.CharField(blank=True, max_length=100)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('minor', models.BooleanField(blank=True, default=False)),
                ('programme', models.CharField(choices=[('btech', 'btech'), ('mtech', 'mtech'), ('msc', 'msc'), ('mdes', 'mdes'), ('bdes', 'bdes'), ('phd', 'phd'), ('msr', 'msr'), ('ma', 'ma')], max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='poc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dday_portal.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='eligibility_criteria',
            field=models.ManyToManyField(related_name='eligible_companies', to='dday_portal.eligible'),
        ),
        migrations.AddField(
            model_name='company',
            name='shortlist_candidate',
            field=models.ManyToManyField(blank=True, related_name='shortlist_person', to='dday_portal.candidate'),
        ),
        migrations.AddField(
            model_name='company',
            name='waiting_candidate',
            field=models.ManyToManyField(blank=True, related_name='waiting_person', to='dday_portal.candidate'),
        ),
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_all', models.BooleanField(blank=True, default=False)),
                ('description', models.CharField(max_length=200)),
                ('poc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dday_portal.poc')),
            ],
        ),
    ]
